### ISSUE TITLE
Не сохраняются задачи в файл

### ISSUE THREAD

**Issue by alforovd** [FaPaH/TaskManager---Java-core#11]
При сохранении задач в файл падает ошибка
`Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.time.LocalDate java.time.LocalDateTime.date accessible: module java.base does not "opens java.time" to unnamed module @23ceabc1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.toJson(Gson.java:696)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:658)
	at ua.edu.sumdu.j2se.radchenko.tasks.model.TaskIO.write(TaskIO.java:91)
	at ua.edu.sumdu.j2se.radchenko.tasks.controller.SaveLoadController.Save(SaveLoadController.java:47)
	at ua.edu.sumdu.j2se.radchenko.tasks.controller.SaveLoadController.process(SaveLoadController.java:28)
	at ua.edu.sumdu.j2se.radchenko.tasks.controller.ControllerImpl.process(ControllerImpl.java:46)
	at ua.edu.sumdu.j2se.radchenko.tasks.controller.ControllerImpl.process(ControllerImpl.java:46)
	at ua.edu.sumdu.j2se.radchenko.tasks.controller.ControllerImpl.process(ControllerImpl.java:46)
	at ua.edu.sumdu.j2se.radchenko.tasks.Main.main(Main.java:18)`

**Comment by FaPaH** [comment]
На счет этого, я не уверен что проблема с моей стороны, так как у меня все работает, но я посижу поищу, может я смогу на своей стороне все же пофиксить это
